#include "comm.hpp"

#if CONTROLLER_IS_JOY_NRF_SHIELD
// CE 9, CSN 10, MOSI 11, MISO 12, SCK 13
RF24 rf_driver(NRF24L01_CE_PIN, NRF24L01_CSN_PIN); 
#else
#if defined(ARDUINO_AVR_UNO)
#if CONTROLLER_COMM_MODULE == CONTROLLER_COMM_MODULE_RF433
// Data pin connects to pin 12
RH_ASK rf_driver;
#elif CONTROLLER_COMM_MODULE == CONTROLLER_COMM_MODULE_NRF24
RF24 rf_driver(NRF24L01_CE_PIN, NRF24L01_CSN_PIN);
#else
#error \
    "Unsupported communication module! Please define CONTROLLER_COMM_MODULE to either CONTROLLER_COMM_MODULE_RF433 or CONTROLLER_COMM_MODULE_NRF24."
#endif  // CONTROLLER_COMM_MODULE
#elif defined(ARDUINO_ESP32_DEV)
#if CONTROLLER_COMM_MODULE == CONTROLLER_COMM_MODULE_RF433
RH_ASK rf_driver(2000, 21, 22);
#elif CONTROLLER_COMM_MODULE == CONTROLLER_COMM_MODULE_NRF24
RF24 rf_driver(NRF24L01_CE_PIN, NRF24L01_CSN_PIN);
#else
#error \
    "Unsupported communication module! Please define CONTROLLER_COMM_MODULE to either CONTROLLER_COMM_MODULE_RF433 or CONTROLLER_COMM_MODULE_NRF24."
#endif  // CONTROLLER_COMM_MODULE
#endif  // ARDUINO_AVR_UNO or ARDUINO_ESP32_DEV
#endif  // CONTROLLER_IS_JOY_NRF_SHIELD

String controlData;

#if CONTROLLER_COMM_MODULE == CONTROLLER_COMM_MODULE_NRF24
// Let these addresses be used for the pair
const uint8_t address[] = "00001";
#endif  // CONTROLLER_COMM_MODULE_NRF24